name: Unit testing calc.py

on: 
  workflow_dispatch:

jobs:
  test_calc:
    runs-on: ubuntu-22.2
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Demo shell commands
        run: |
          pwd
          echo "Hello"
          ls -la
          
        
    